-- Adminer 4.8.1 PostgreSQL 17.2 (Debian 17.2-1.pgdg120+1) dump

DROP TABLE IF EXISTS "album_artist";
CREATE TABLE "public"."album_artist" (
                                         "album_id" integer NOT NULL,
                                         "artist_id" integer NOT NULL,
                                         CONSTRAINT "album_artist_pkey" PRIMARY KEY ("album_id", "artist_id")
) WITH (oids = false);

INSERT INTO "album_artist" ("album_id", "artist_id") VALUES
                                                         (1,	1),
                                                         (2,	2),
                                                         (2,	3),
                                                         (3,	4);

DROP TABLE IF EXISTS "albums";
CREATE TABLE "public"."albums" (
                                   "album_id" integer DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                   "title" character varying(100),
                                   "release_date" date,
                                   "picture" character varying(255),
                                   "spotify_id" character varying(100),
                                   CONSTRAINT "albums_pkey" PRIMARY KEY ("album_id")
) WITH (oids = false);

INSERT INTO "albums" ("album_id", "title", "release_date", "picture", "spotify_id") VALUES
                                                                                        (1,	'Tell Me Moon',	'2025-02-21',	'https://i.scdn.co/image/ab67616d0000b273598762e4f6744b359145084a',	'2kHHOGhg3nC4LawypsYdqC'),
                                                                                        (2,	'เรื่องเล่าของเจ้าหญิง (A Princess'' Tale) [เพลงประกอบซีรีส์ "Pluto นิทาน ดวงดาว ความรัก"]',	'2024-10-30',	'https://i.scdn.co/image/ab67616d0000b27313254ce60b7885cccef857da',	'4Qvmi0BXFCX03s4ReFOxiD'),
                                                                                        (3,	'Why - The 2nd Mini Album',	'2016-06-28',	'https://i.scdn.co/image/ab67616d0000b273e4915763c3c7f7a05cc93885',	'1ukBQWhQwWKqTGgs0YzRzU');

DROP TABLE IF EXISTS "artists";
CREATE TABLE "public"."artists" (
                                    "artist_id" integer DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                    "name" character varying(100),
                                    "genre" character varying(50),
                                    "picture" character varying(255),
                                    "spotify_id" character varying(100),
                                    CONSTRAINT "artists_pkey" PRIMARY KEY ("artist_id")
) WITH (oids = false);

INSERT INTO "artists" ("artist_id", "name", "genre", "picture", "spotify_id") VALUES
                                                                                  (1,	'Okomo P',	'Unknown',	'https://i.scdn.co/image/ab67616d0000b273598762e4f6744b359145084a',	'71wrDZRYadma6qaodkVHev'),
                                                                                  (2,	'Namtan Tipnaree',	'Unknown',	'https://i.scdn.co/image/ab67616d0000b27313254ce60b7885cccef857da',	'3nJfC4MkZ0lmOpYMs5IXKe'),
                                                                                  (3,	'Film Rachanun',	'Unknown',	'https://i.scdn.co/image/ab67616d0000b27313254ce60b7885cccef857da',	'0AjdwTUow88qbVEDXifQAy'),
                                                                                  (4,	'TAEYEON',	'Unknown',	'https://i.scdn.co/image/ab6761610000e5ebb5d9ebbbbe3fff5a330b40c8',	'3qNVuliS40BLgXGxhdBdqu');

DROP TABLE IF EXISTS "cache";
CREATE TABLE "public"."cache" (
                                  "key" character varying(255) NOT NULL,
                                  "value" text NOT NULL,
                                  "expiration" integer NOT NULL,
                                  CONSTRAINT "cache_pkey" PRIMARY KEY ("key")
) WITH (oids = false);


DROP TABLE IF EXISTS "cache_locks";
CREATE TABLE "public"."cache_locks" (
                                        "key" character varying(255) NOT NULL,
                                        "owner" character varying(255) NOT NULL,
                                        "expiration" integer NOT NULL,
                                        CONSTRAINT "cache_locks_pkey" PRIMARY KEY ("key")
) WITH (oids = false);


DROP TABLE IF EXISTS "failed_jobs";
DROP SEQUENCE IF EXISTS failed_jobs_id_seq;
CREATE SEQUENCE failed_jobs_id_seq INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;

CREATE TABLE "public"."failed_jobs" (
                                        "id" bigint DEFAULT nextval('failed_jobs_id_seq') NOT NULL,
                                        "uuid" character varying(255) NOT NULL,
                                        "connection" text NOT NULL,
                                        "queue" text NOT NULL,
                                        "payload" text NOT NULL,
                                        "exception" text NOT NULL,
                                        "failed_at" timestamp(0) DEFAULT CURRENT_TIMESTAMP NOT NULL,
                                        CONSTRAINT "failed_jobs_pkey" PRIMARY KEY ("id"),
                                        CONSTRAINT "failed_jobs_uuid_unique" UNIQUE ("uuid")
) WITH (oids = false);


DROP TABLE IF EXISTS "job_batches";
CREATE TABLE "public"."job_batches" (
                                        "id" character varying(255) NOT NULL,
                                        "name" character varying(255) NOT NULL,
                                        "total_jobs" integer NOT NULL,
                                        "pending_jobs" integer NOT NULL,
                                        "failed_jobs" integer NOT NULL,
                                        "failed_job_ids" text NOT NULL,
                                        "options" text,
                                        "cancelled_at" integer,
                                        "created_at" integer NOT NULL,
                                        "finished_at" integer,
                                        CONSTRAINT "job_batches_pkey" PRIMARY KEY ("id")
) WITH (oids = false);


DROP TABLE IF EXISTS "jobs";
DROP SEQUENCE IF EXISTS jobs_id_seq;
CREATE SEQUENCE jobs_id_seq INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;

CREATE TABLE "public"."jobs" (
                                 "id" bigint DEFAULT nextval('jobs_id_seq') NOT NULL,
                                 "queue" character varying(255) NOT NULL,
                                 "payload" text NOT NULL,
                                 "attempts" smallint NOT NULL,
                                 "reserved_at" integer,
                                 "available_at" integer NOT NULL,
                                 "created_at" integer NOT NULL,
                                 CONSTRAINT "jobs_pkey" PRIMARY KEY ("id")
) WITH (oids = false);

CREATE INDEX "jobs_queue_index" ON "public"."jobs" USING btree ("queue");


DROP TABLE IF EXISTS "lyrics";
CREATE TABLE "public"."lyrics" (
                                   "lyrics_id" integer DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                   "song_id" integer,
                                   "lyrics_content" text,
                                   "timestamp" time without time zone,
                                   CONSTRAINT "lyrics_pkey" PRIMARY KEY ("lyrics_id")
) WITH (oids = false);


DROP TABLE IF EXISTS "migrations";
DROP SEQUENCE IF EXISTS migrations_id_seq;
CREATE SEQUENCE migrations_id_seq INCREMENT 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1;

CREATE TABLE "public"."migrations" (
                                       "id" integer DEFAULT nextval('migrations_id_seq') NOT NULL,
                                       "migration" character varying(255) NOT NULL,
                                       "batch" integer NOT NULL,
                                       CONSTRAINT "migrations_pkey" PRIMARY KEY ("id")
) WITH (oids = false);

INSERT INTO "migrations" ("id", "migration", "batch") VALUES
                                                          (1,	'0001_01_01_000000_create_users_table',	1),
                                                          (2,	'0001_01_01_000001_create_cache_table',	1),
                                                          (3,	'0001_01_01_000002_create_jobs_table',	1),
                                                          (4,	'2025_04_21_073328_create_personal_access_tokens_table',	1),
                                                          (5,	'2025_04_26_102933_add_picture_to_users_table',	1),
                                                          (6,	'2025_04_26_110302_add_provider_to_users_table',	1);

DROP TABLE IF EXISTS "password_reset_tokens";
CREATE TABLE "public"."password_reset_tokens" (
                                                  "email" character varying(255) NOT NULL,
                                                  "token" character varying(255) NOT NULL,
                                                  "created_at" timestamp(0),
                                                  CONSTRAINT "password_reset_tokens_pkey" PRIMARY KEY ("email")
) WITH (oids = false);


DROP TABLE IF EXISTS "personal_access_tokens";
DROP SEQUENCE IF EXISTS personal_access_tokens_id_seq;
CREATE SEQUENCE personal_access_tokens_id_seq INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;

CREATE TABLE "public"."personal_access_tokens" (
                                                   "id" bigint DEFAULT nextval('personal_access_tokens_id_seq') NOT NULL,
                                                   "tokenable_type" character varying(255) NOT NULL,
                                                   "tokenable_id" bigint NOT NULL,
                                                   "name" character varying(255) NOT NULL,
                                                   "token" character varying(64) NOT NULL,
                                                   "abilities" text,
                                                   "last_used_at" timestamp(0),
                                                   "expires_at" timestamp(0),
                                                   "created_at" timestamp(0),
                                                   "updated_at" timestamp(0),
                                                   CONSTRAINT "personal_access_tokens_pkey" PRIMARY KEY ("id"),
                                                   CONSTRAINT "personal_access_tokens_token_unique" UNIQUE ("token")
) WITH (oids = false);

CREATE INDEX "personal_access_tokens_tokenable_type_tokenable_id_index" ON "public"."personal_access_tokens" USING btree ("tokenable_type", "tokenable_id");


DROP TABLE IF EXISTS "playlist_songs";
CREATE TABLE "public"."playlist_songs" (
                                           "playlist_id" integer,
                                           "song_id" integer
) WITH (oids = false);


DROP TABLE IF EXISTS "playlists";
CREATE TABLE "public"."playlists" (
                                      "playlist_id" integer DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                      "user_id" integer,
                                      "playlist_name" character varying(100),
                                      "created_at" timestamp,
                                      CONSTRAINT "playlists_pkey" PRIMARY KEY ("playlist_id")
) WITH (oids = false);


DROP TABLE IF EXISTS "sessions";
CREATE TABLE "public"."sessions" (
                                     "id" character varying(255) NOT NULL,
                                     "user_id" bigint,
                                     "ip_address" character varying(45),
                                     "user_agent" text,
                                     "payload" text NOT NULL,
                                     "last_activity" integer NOT NULL,
                                     CONSTRAINT "sessions_pkey" PRIMARY KEY ("id")
) WITH (oids = false);

CREATE INDEX "sessions_last_activity_index" ON "public"."sessions" USING btree ("last_activity");

CREATE INDEX "sessions_user_id_index" ON "public"."sessions" USING btree ("user_id");


DROP TABLE IF EXISTS "song_artist";
CREATE TABLE "public"."song_artist" (
                                        "song_id" integer NOT NULL,
                                        "artist_id" integer NOT NULL,
                                        CONSTRAINT "song_artist_pkey" PRIMARY KEY ("song_id", "artist_id")
) WITH (oids = false);


DROP TABLE IF EXISTS "song_history";
CREATE TABLE "public"."song_history" (
                                         "history_id" integer DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                         "user_id" integer,
                                         "song_id" integer,
                                         "played_at" timestamp,
                                         CONSTRAINT "song_history_pkey" PRIMARY KEY ("history_id")
) WITH (oids = false);


DROP TABLE IF EXISTS "songs";
CREATE TABLE "public"."songs" (
                                  "song_id" integer DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                  "title" character varying(100),
                                  "duration" time without time zone,
                                  "album_id" integer,
                                  "file_path" character varying(255),
                                  "spotify_id" character varying(100),
                                  "picture" character varying(255),
                                  CONSTRAINT "songs_pkey" PRIMARY KEY ("song_id")
) WITH (oids = false);

INSERT INTO "songs" ("song_id", "title", "duration", "album_id", "file_path", "spotify_id", "picture") VALUES
                                                                                                           (1,	'Tell Me Moon',	'00:04:24',	1,	'/songs/OKOMO P - Tell Me Moon.mp3',	'1vTnzA7PVfr4GG62cvTAy4',	'https://i.scdn.co/image/ab67616d0000b273598762e4f6744b359145084a'),
                                                                                                           (2,	'เรื่องเล่าของเจ้าหญิง (A Princess'' Tale) - เพลงประกอบซีรีส์ "Pluto นิทาน ดวงดาว ความรัก"',	'00:03:37',	2,	'/songs/Pluto''s OST. A princesss tale.mp3',	'65bTNAQUxdExNka5guhsEF',	'https://i.scdn.co/image/ab67616d0000b27313254ce60b7885cccef857da'),
                                                                                                           (4,	'Starlight',	'00:03:43',	3,	'/songs/Starlight  (Feat. DEAN).mp3',	'5MYL9WejirHj0kc8crJPJ0',	'https://i.scdn.co/image/ab67616d0000b273e4915763c3c7f7a05cc93885'),
                                                                                                           (5,	'Fashion',	'00:03:12',	3,	'/songs/Fashion.mp3',	'4AEvnRVdOq4GHx5vFvDDTh',	'https://i.scdn.co/image/ab67616d0000b273e4915763c3c7f7a05cc93885'),
                                                                                                           (6,	'Hands on Me',	'00:03:48',	3,	'/songs/Hands on Me.mp3',	'4meLiOL9ns3ZvlldHcSB9p',	'https://i.scdn.co/image/ab67616d0000b273e4915763c3c7f7a05cc93885'),
                                                                                                           (7,	'Up & Down',	'00:02:53',	3,	'/songs/Up & Down.mp3',	'2T20Nb7QlVK8K6pRSiDl8N',	'https://i.scdn.co/image/ab67616d0000b273e4915763c3c7f7a05cc93885'),
                                                                                                           (8,	'Good Thing',	'00:02:57',	3,	'/songs/Good Thing.mp3',	'30CAqzLOdc8LbPRzchYaAt',	'https://i.scdn.co/image/ab67616d0000b273e4915763c3c7f7a05cc93885'),
                                                                                                           (9,	'Night',	'00:03:13',	3,	'/songs/Night.mp3',	'26X50tiIvOem3M7pvJ2bm5',	'https://i.scdn.co/image/ab67616d0000b273e4915763c3c7f7a05cc93885'),
                                                                                                           (3,	'Why',	'00:03:27',	3,	'/songs/태연 ''Why''.mp3',	'4eiPbjcTEJDQcsv7WV0vfD',	'https://i.scdn.co/image/ab67616d0000b273e4915763c3c7f7a05cc93885');

DROP TABLE IF EXISTS "users";
DROP SEQUENCE IF EXISTS users_id_seq;
CREATE SEQUENCE users_id_seq INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;

CREATE TABLE "public"."users" (
                                  "id" bigint DEFAULT nextval('users_id_seq') NOT NULL,
                                  "name" character varying(255) NOT NULL,
                                  "email" character varying(255) NOT NULL,
                                  "email_verified_at" timestamp(0),
                                  "password" character varying(255) NOT NULL,
                                  "remember_token" character varying(100),
                                  "created_at" timestamp(0),
                                  "updated_at" timestamp(0),
                                  "picture" character varying(255),
                                  "provider" character varying(255),
                                  CONSTRAINT "users_email_unique" UNIQUE ("email"),
                                  CONSTRAINT "users_pkey" PRIMARY KEY ("id")
) WITH (oids = false);


ALTER TABLE ONLY "public"."album_artist" ADD CONSTRAINT "album_artist_album_id_fkey" FOREIGN KEY (album_id) REFERENCES albums(album_id) ON DELETE CASCADE NOT DEFERRABLE;
ALTER TABLE ONLY "public"."album_artist" ADD CONSTRAINT "album_artist_artist_id_fkey" FOREIGN KEY (artist_id) REFERENCES artists(artist_id) ON DELETE CASCADE NOT DEFERRABLE;

ALTER TABLE ONLY "public"."lyrics" ADD CONSTRAINT "lyrics_song_id_fkey" FOREIGN KEY (song_id) REFERENCES songs(song_id) NOT DEFERRABLE;

ALTER TABLE ONLY "public"."playlist_songs" ADD CONSTRAINT "playlist_songs_playlist_id_fkey" FOREIGN KEY (playlist_id) REFERENCES playlists(playlist_id) NOT DEFERRABLE;
ALTER TABLE ONLY "public"."playlist_songs" ADD CONSTRAINT "playlist_songs_song_id_fkey" FOREIGN KEY (song_id) REFERENCES songs(song_id) NOT DEFERRABLE;
ALTER TABLE ONLY "public"."playlist_songs" ADD CONSTRAINT "playlist_songs_song_id_fkey1" FOREIGN KEY (song_id) REFERENCES songs(song_id) NOT DEFERRABLE;

ALTER TABLE ONLY "public"."playlists" ADD CONSTRAINT "playlists_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) NOT DEFERRABLE;

ALTER TABLE ONLY "public"."song_artist" ADD CONSTRAINT "song_artist_song_fkey" FOREIGN KEY (song_id) REFERENCES songs(song_id) ON DELETE CASCADE NOT DEFERRABLE;
ALTER TABLE ONLY "public"."song_artist" ADD CONSTRAINT "song_artistt_artist_id_fkey" FOREIGN KEY (artist_id) REFERENCES artists(artist_id) ON DELETE CASCADE NOT DEFERRABLE;

ALTER TABLE ONLY "public"."song_history" ADD CONSTRAINT "song_history_song_id_fkey" FOREIGN KEY (song_id) REFERENCES songs(song_id) NOT DEFERRABLE;
ALTER TABLE ONLY "public"."song_history" ADD CONSTRAINT "song_history_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) NOT DEFERRABLE;

ALTER TABLE ONLY "public"."songs" ADD CONSTRAINT "songs_album_id_fkey" FOREIGN KEY (album_id) REFERENCES albums(album_id) NOT DEFERRABLE;

-- 2025-07-07 14:57:20.15515+00