-- Adminer 4.8.1 PostgreSQL 17.2 (Debian 17.2-1.pgdg120+1) dump

DROP TABLE IF EXISTS "album_artist";
CREATE TABLE "public"."album_artist" (
                                         "album_id" integer NOT NULL,
                                         "artist_id" integer NOT NULL,
                                         CONSTRAINT "album_artist_pkey" PRIMARY KEY ("album_id", "artist_id")
) WITH (oids = false);


DROP TABLE IF EXISTS "albums";
CREATE TABLE "public"."albums" (
                                   "album_id" integer DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                   "title" character varying(100),
                                   "release_date" date,
                                   "picture" character varying(255),
                                   "spotify_id" character varying(100),
                                   CONSTRAINT "albums_pkey" PRIMARY KEY ("album_id")
) WITH (oids = false);


DROP TABLE IF EXISTS "artists";
CREATE TABLE "public"."artists" (
                                    "artist_id" integer DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                    "name" character varying(100),
                                    "genre" character varying(50),
                                    "picture" character varying(255),
                                    "spotify_id" character varying(100),
                                    CONSTRAINT "artists_pkey" PRIMARY KEY ("artist_id")
) WITH (oids = false);


DROP TABLE IF EXISTS "lyrics";
CREATE TABLE "public"."lyrics" (
                                   "lyrics_id" integer DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                   "song_id" integer,
                                   "lyrics_content" text,
                                   "timestamp" time without time zone,
                                   CONSTRAINT "lyrics_pkey" PRIMARY KEY ("lyrics_id")
) WITH (oids = false);


DROP TABLE IF EXISTS "playlist_songs";
CREATE TABLE "public"."playlist_songs" (
                                           "playlist_id" integer,
                                           "song_id" integer
) WITH (oids = false);


DROP TABLE IF EXISTS "playlists";
CREATE TABLE "public"."playlists" (
                                      "playlist_id" integer DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                      "user_id" integer,
                                      "playlist_name" character varying(100),
                                      "created_at" timestamp,
                                      CONSTRAINT "playlists_pkey" PRIMARY KEY ("playlist_id")
) WITH (oids = false);


DROP TABLE IF EXISTS "song_artist";
CREATE TABLE "public"."song_artist" (
                                        "song_id" integer NOT NULL,
                                        "artist_id" integer NOT NULL,
                                        CONSTRAINT "song_artist_pkey" PRIMARY KEY ("song_id", "artist_id")
) WITH (oids = false);


DROP TABLE IF EXISTS "song_history";
CREATE TABLE "public"."song_history" (
                                         "history_id" integer DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                         "user_id" integer,
                                         "song_id" integer,
                                         "played_at" timestamp,
                                         CONSTRAINT "song_history_pkey" PRIMARY KEY ("history_id")
) WITH (oids = false);


DROP TABLE IF EXISTS "songs";
CREATE TABLE "public"."songs" (
                                  "song_id" integer DEFAULT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                  "title" character varying(100),
                                  "duration" time without time zone,
                                  "album_id" integer,
                                  "file_path" character varying(255),
                                  "spotify_id" character varying(100),
                                  "picture" character varying(255),
                                  CONSTRAINT "songs_pkey" PRIMARY KEY ("song_id")
) WITH (oids = false);


DROP TABLE IF EXISTS "users";
DROP SEQUENCE IF EXISTS users_id_seq;
CREATE SEQUENCE users_id_seq INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1;

CREATE TABLE "public"."users" (
                                  "id" bigint DEFAULT nextval('users_id_seq') NOT NULL,
                                  "name" character varying(255) NOT NULL,
                                  "email" character varying(255) NOT NULL,
                                  "email_verified_at" timestamp(0),
                                  "password" character varying(255) NOT NULL,
                                  "remember_token" character varying(100),
                                  "created_at" timestamp(0),
                                  "updated_at" timestamp(0),
                                  "picture" character varying(255),
                                  "provider" character varying(255),
                                  CONSTRAINT "users_email_unique" UNIQUE ("email"),
                                  CONSTRAINT "users_pkey" PRIMARY KEY ("id")
) WITH (oids = false);


ALTER TABLE ONLY "public"."album_artist" ADD CONSTRAINT "album_artist_album_id_fkey" FOREIGN KEY (album_id) REFERENCES albums(album_id) ON DELETE CASCADE NOT DEFERRABLE;
ALTER TABLE ONLY "public"."album_artist" ADD CONSTRAINT "album_artist_artist_id_fkey" FOREIGN KEY (artist_id) REFERENCES artists(artist_id) ON DELETE CASCADE NOT DEFERRABLE;

ALTER TABLE ONLY "public"."lyrics" ADD CONSTRAINT "lyrics_song_id_fkey" FOREIGN KEY (song_id) REFERENCES songs(song_id) NOT DEFERRABLE;

ALTER TABLE ONLY "public"."playlist_songs" ADD CONSTRAINT "playlist_songs_playlist_id_fkey" FOREIGN KEY (playlist_id) REFERENCES playlists(playlist_id) NOT DEFERRABLE;
ALTER TABLE ONLY "public"."playlist_songs" ADD CONSTRAINT "playlist_songs_song_id_fkey" FOREIGN KEY (song_id) REFERENCES songs(song_id) NOT DEFERRABLE;
ALTER TABLE ONLY "public"."playlist_songs" ADD CONSTRAINT "playlist_songs_song_id_fkey1" FOREIGN KEY (song_id) REFERENCES songs(song_id) NOT DEFERRABLE;

ALTER TABLE ONLY "public"."playlists" ADD CONSTRAINT "playlists_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) NOT DEFERRABLE;

ALTER TABLE ONLY "public"."song_artist" ADD CONSTRAINT "song_artist_song_fkey" FOREIGN KEY (song_id) REFERENCES songs(song_id) ON DELETE CASCADE NOT DEFERRABLE;
ALTER TABLE ONLY "public"."song_artist" ADD CONSTRAINT "song_artistt_artist_id_fkey" FOREIGN KEY (artist_id) REFERENCES artists(artist_id) ON DELETE CASCADE NOT DEFERRABLE;

ALTER TABLE ONLY "public"."song_history" ADD CONSTRAINT "song_history_song_id_fkey" FOREIGN KEY (song_id) REFERENCES songs(song_id) NOT DEFERRABLE;
ALTER TABLE ONLY "public"."song_history" ADD CONSTRAINT "song_history_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) NOT DEFERRABLE;

ALTER TABLE ONLY "public"."songs" ADD CONSTRAINT "songs_album_id_fkey" FOREIGN KEY (album_id) REFERENCES albums(album_id) NOT DEFERRABLE;

-- 2025-08-03 12:38:45.461175+00